project:
  type: book
  output-dir: docs 

book:
  title: "ğŸ“š ExperimentaÃ§Ã£o Florestal com R"
  subtitle: "Uma jornada prÃ¡tica de EstatÃ­stica Experimental"
  author: "Edgar de Souza Vismara"
  date: today
  cover-image: cover.png # <â€” caminho da capa
  chapters:
    - index.qmd
    - cap01-introducao.qmd
    - cap02-variaveis-fatores.qmd
    - cap03A-anova.qmd
    - cap03B-anova2.qmd
    - cap04-delineamentos.qmd
    - cap05-contrastes.qmd
    - cap06-fatorial.qmd
    - cap07-split.qmd
    - cap08-regre.qmd
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles/custom.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-overflow: wrap
    code-fold: true
    lang: pt
  

execute:
  echo: true
  warning: false
  message: false